### ISSUE TITLE
"AnsibleUndefinedVariable: 'mounts' is undefined"

### ISSUE THREAD

**Issue by charlesg** [cmprescott/ansible-role-autofs#10]
I'm somewhat new to ansible and considering it for System Mgmt tasks. So your autofs role caught my attention. 

In testing, I'm running in an error:

```
TASK [autofs : Config| all | create indirect map file(s) from template] ********
failed: [cgagnon-ln1] (item={u'mounts': [{u'url': u'hcfiler1:/vol/backupsnj', u'name': u'backupsnj', u'fstype': u'nfs,rw,nosuid'}, {u'url': u'hcnex1:/volumes/root/ivydb', u'name': u'ivydb', u'fstype': u'nfs,rw,nosuid'}], u'path': u'/mnt/test', u'name': u'autofs.test'}) => {"failed": true, "item": {"mounts": [{"fstype": "nfs,rw,nosuid", "name": "backupsnj", "url": "hcfiler1:/vol/backupsnj"}, {"fstype": "nfs,rw,nosuid", "name": "ivydb", "url": "hcnex1:/volumes/root/ivydb"}], "name": "autofs.test", "path": "/mnt/test"}, "msg": "AnsibleUndefinedVariable: 'mounts' is undefined"}
```

My test playbook has the below (which include 'mounts'). Any tips on troubleshooting this?

``` yaml
- hosts: cgagnon-ln1
  vars:
    autofs_indirect_maps:
    - name: autofs.test
      path: /mnt/test
      mounts:
        - name: "backupsnj"
          fstype: "nfs,rw,nosuid"
          url: "hcfiler1:/vol/backupsnj"
        - name: "ivydb"
          fstype: "nfs,rw,nosuid"
          url: "hcnex1:/volumes/root/ivydb"
  roles:
    - role: autofs
      sudo: Yes
```

**Comment by cmprescott** [comment]
I think I screwed up the documentation vs. actually variable names. Let me double check that.

-PS use "```yaml" for you you post snippets. The markdown formatting makes it hard to read.

``` yaml
- hosts: cgagnon-ln1
  vars:
    autofs_indirect_maps:
    - name: autofs.test
      path: /mnt/test
      mounts:
        - name: "backupsnj"
          fstype: "nfs,rw,nosuid"
          url: "hcfiler1:/vol/backupsnj"
        - name: "ivydb"
          fstype: "nfs,rw,nosuid"
          url: "hcnex1:/volumes/root/ivydb"
  roles:
    - role: autofs
      sudo: Yes
```

**Comment by cmprescott** [comment]
Must have been thinking of something else. Looks like the variable names are correct. Maybe try without defining in the vars? Also, what ansible version are you using?

``` yaml
- hosts: cgagnon-ln1
  vars:
  roles:
    - role: autofs
      sudo: Yes
      autofs_indirect_maps:
        - name: autofs.test
          path: /mnt/test
          mounts:
            - name: "backupsnj"
              fstype: "nfs,rw,nosuid"
              url: "hcfiler1:/vol/backupsnj"
            - name: "ivydb"
              fstype: "nfs,rw,nosuid"
              url: "hcnex1:/volumes/root/ivydb"
```
